---
title: "Affirmative Action or Privilege?"
date: "2011-09-08"
categories: 
  - "perspectives"
---

Dr. Anthony Bradley, author of the new book _Black and Tired: Essays on Race, Politics, Culture, and International Development_, spoke at the Heritage Foundation about his research on the downward moral trend of black culture in America.

As an associate professor of theology at King’s College in New York, Dr. Bradley demonstrated his thorough knowledge and experience throughout the book event. He referred to American exceptionalism with a personal anecdote, of how his relatives own the plantation where their ancestors were enslaved. He pointed out that “there are not many other countries around the world where subdominant cultures rise to that level, that status” of equality from the depths of slavery.

Dr. Bradley saw that the principles that made America great are now “being sabotaged and eroded by those who have good intentions, but often do not think through the consequences of [their decisions],” where the “black underclass” has been the most affected culture by these decisions. He said that by “concentrating power in the hands of a few people leads to more oppression, not less,” and that this has been the story of the “black experience in America.” He regretfully acknowledged that the civil rights movement of Dr. Martin Luther King, Rosa Parks, and others has been “hijacked by the organizational narcissism that we find among politicians…operating under the delusion that [they have the] expertise and capacity to solve society’s problems.” Also, he explained that the basis of the civil rights movement was a search for human dignity for the black community, and today it is about “zero sum economics” and “as if life were a race, or a competition.”

He admitted that he sits “on the same political island as Thomas Sowel, and Walter Williams, friendless, with the understanding…economic liberation…is inseparable from honoring the dignity of blackness.” As a religious man himself, Dr. Bradley noted that the current decay in the black community has occurred because “the less religion in society, the more people turn to government”. In citing Alexis de Toqueville, he made the point that without religion in society, an “inordinate love for material gratification” will lead democracy in the wrong direction. De Toqueville recognized that religion exists“to purify, control, and restrain the exclusive taste…that men acquire in times of equality.” Today, he said, some see socialism and communism as a fight “for justified injustice…it’s called ‘people doing their fair share.’” The civil rights movement has shifted from human dignity, “derailed” by politics and “bling,” in choosing political clout as a means of equality over the marketplace. Other ethnic groups, Dr. Bradley pointed out, “chose the marketplace as a means of social and economic mobility as opposed to politics.”

Referring to flash mob thieves, as he called them, Dr. Bradley suggested bringing them to the statue of Dr. Martin Luther King and asking, “What would Dr. King say to you right now?” He saw these actions as an affront to the civil rights movement and Dr. King’s dream of equality; “Every time a flash mob steals, it’s robbing King of his dream, from Philadelphia to Chicago to here in Washington, D.C.” In place of progress and achievement, “young people are trading…[for an] adrenaline rush of stealing from others.” As the speaker noted, Dr. King taught that “political and social frustration…does not justify breaking the law.” He then posed several questions on how society neglects “forming the youth into people of character,” or how society raises the youth on “class warfare” and “redistribution” and yet is surprised when flash mob thieves rule the headlines. “Radical individual and moral relativism” now defines society as the “criminal flash mobs expose [society’s] progressive failure.” The absence of morality, which Bradley believes “could end the recession for good,” has only exacerbated today’s societal problems. He strongly advocates the belief “that a resurgence of virtue would give rise to a generation of moral and law-abiding citizens,” and help the black community rise from their dependent state to realize Dr. King’s dream.

Dr. Bradley cited a study in Howard University’s Journal of Negro Education, a respected academic journal, of how black teenagers who attend church services often are more likely to receive a college education. The study also found that the black-white student achievement gap “was eliminated” when black students attended church services often. Possible reasons for thse results, according to the Dr. Bradley, are that black churches provide mentors and role models, and that parents have the opportunity to teach from the heart based on religious values.

He then described the problems of raising the minimum wage for the black community. More often than not, Dr. Bradley said, people do not think of long-term consequences of raising the minimum wage. He firmly believes it “hurts minorities, it actually hurts teens, those who don’t have skills.” As a result, businesses will employ smaller amounts of less skilled, minimum-wage workers because the cost of employing them increases with higher wages. He noted that the money to pay the wage increase “doesn’t magically appear. It has to come from somewhere.” Other consequences of raising the minimum wage include laying off low-skilled workers, skirting employment laws, hiring illegals, under-the-table payment of employees, or moving jobs elsewhere. UConn professor Kenneth Couch estimated that for every $1 rise in the minimum wage reduces teenage employment opportunity by 140,000 jobs.

The underlying problem of the business world, according to Dr. Bradley, is the “racist ideology” that “blacks don’t think, they are told what to do.” Some view themselves as elites, or what he terms as “surrogate third parties,” who then manage and make decisions for the masses. The existence of these elites, as Dr. Bradley stated, “was the black experience during slavery and Jim Crow.” The resolution to this problem is “political and social empowerment” of the black community that will occur when society recognizes that power in the hands of a few elites undermines human dignity. Dr. Bradley believes that “this nation will go bankrupt”  if these social and economic issues are not resolved. As he sees it, “the hip-hop generation represents the most ‘un-churched’ group of African Americans since the plantation.”

_Spencer Irvine is a research assistant at Accuracy in Academia._

If you would like to comment on this article, e-mail [**mal.kline@academia.org**](mailto:mal.kline@academia.org)
